// <auto-generated>
// Generated from ESPHome api.proto
// Repo: https://github.com/esphome/esphome/blob/dev/esphome/components/api/api.proto
// NOTE: Regenerate whenever you update ESPHome (IDs or RPCs may change).
// </auto-generated>

using System;
using System.Threading;
using System.Threading.Tasks;
using System.Net.Sockets;

namespace ESPHome_Server
{
    /// <summary>
    /// ESPHome Native API message type IDs (wire preamble VarInt).
    /// Source: api.proto option(id)=N
    /// </summary>
    public enum EspHomeApiMessageId
    {
        HelloRequest = 1,
        HelloResponse = 2,
        AuthenticationRequest = 3,
        AuthenticationResponse = 4,
        DisconnectRequest = 5,
        DisconnectResponse = 6,
        PingRequest = 7,
        PingResponse = 8,
        DeviceInfoRequest = 9,
        DeviceInfoResponse = 10,
        ListEntitiesRequest = 11,
        ListEntitiesBinarySensorResponse = 12,
        ListEntitiesCoverResponse = 13,
        ListEntitiesFanResponse = 14,
        ListEntitiesLightResponse = 15,
        ListEntitiesSensorResponse = 16,
        ListEntitiesSwitchResponse = 17,
        ListEntitiesTextSensorResponse = 18,
        ListEntitiesDoneResponse = 19,
        SubscribeStatesRequest = 20,
        BinarySensorStateResponse = 21,
        CoverStateResponse = 22,
        FanStateResponse = 23,
        LightStateResponse = 24,
        SensorStateResponse = 25,
        SwitchStateResponse = 26,
        TextSensorStateResponse = 27,
        SubscribeLogsRequest = 28,
        SubscribeLogsResponse = 29,
        CoverCommandRequest = 30,
        FanCommandRequest = 31,
        LightCommandRequest = 32,
        SwitchCommandRequest = 33,
        SubscribeHomeassistantServicesRequest = 34,
        HomeassistantActionRequest = 35,
        GetTimeRequest = 36,
        GetTimeResponse = 37,
        SubscribeHomeAssistantStatesRequest = 38,
        SubscribeHomeAssistantStateResponse = 39,
        HomeAssistantStateResponse = 40,
        ListEntitiesServicesResponse = 41,
        ExecuteServiceRequest = 42,
        ListEntitiesCameraResponse = 43,
        CameraImageResponse = 44,
        CameraImageRequest = 45,
        ListEntitiesClimateResponse = 46,
        ClimateStateResponse = 47,
        ClimateCommandRequest = 48,
        ListEntitiesNumberResponse = 49,
        NumberStateResponse = 50,
        NumberCommandRequest = 51,
        ListEntitiesSelectResponse = 52,
        SelectStateResponse = 53,
        SelectCommandRequest = 54,
        ListEntitiesSirenResponse = 55,
        SirenStateResponse = 56,
        SirenCommandRequest = 57,
        ListEntitiesLockResponse = 58,
        LockStateResponse = 59,
        LockCommandRequest = 60,
        ListEntitiesButtonResponse = 61,
        ButtonCommandRequest = 62,
        ListEntitiesMediaPlayerResponse = 63,
        MediaPlayerStateResponse = 64,
        MediaPlayerCommandRequest = 65,
        SubscribeBluetoothLEAdvertisementsRequest = 66,
        BluetoothLEAdvertisementResponse = 67,
        BluetoothDeviceRequest = 68,
        BluetoothDeviceConnectionResponse = 69,
        BluetoothGATTGetServicesRequest = 70,
        BluetoothGATTGetServicesResponse = 71,
        BluetoothGATTGetServicesDoneResponse = 72,
        BluetoothGATTReadRequest = 73,
        BluetoothGATTReadResponse = 74,
        BluetoothGATTWriteRequest = 75,
        BluetoothGATTReadDescriptorRequest = 76,
        BluetoothGATTWriteDescriptorRequest = 77,
        BluetoothGATTNotifyRequest = 78,
        BluetoothGATTNotifyDataResponse = 79,
        SubscribeBluetoothConnectionsFreeRequest = 80,
        BluetoothConnectionsFreeResponse = 81,
        BluetoothGATTErrorResponse = 82,
        BluetoothGATTWriteResponse = 83,
        BluetoothGATTNotifyResponse = 84,
        BluetoothDevicePairingResponse = 85,
        BluetoothDeviceUnpairingResponse = 86,
        UnsubscribeBluetoothLEAdvertisementsRequest = 87,
        BluetoothDeviceClearCacheResponse = 88,
        SubscribeVoiceAssistantRequest = 89,
        VoiceAssistantRequest = 90,
        VoiceAssistantResponse = 91,
        VoiceAssistantEventResponse = 92,
        BluetoothLERawAdvertisementsResponse = 93,
        ListEntitiesAlarmControlPanelResponse = 94,
        AlarmControlPanelStateResponse = 95,
        AlarmControlPanelCommandRequest = 96,
        ListEntitiesTextResponse = 97,
        TextStateResponse = 98,
        TextCommandRequest = 99,
        ListEntitiesDateResponse = 100,
        DateStateResponse = 101,
        DateCommandRequest = 102,
        ListEntitiesTimeResponse = 103,
        TimeStateResponse = 104,
        TimeCommandRequest = 105,
        VoiceAssistantAudio = 106,
        ListEntitiesEventResponse = 107,
        EventResponse = 108,
        ListEntitiesValveResponse = 109,
        ValveStateResponse = 110,
        ValveCommandRequest = 111,
        ListEntitiesDateTimeResponse = 112,
        DateTimeStateResponse = 113,
        DateTimeCommandRequest = 114,
        VoiceAssistantTimerEventResponse = 115,
        ListEntitiesUpdateResponse = 116,
        UpdateStateResponse = 117,
        UpdateCommandRequest = 118,
        VoiceAssistantAnnounceRequest = 119,
        VoiceAssistantAnnounceFinished = 120,
        VoiceAssistantConfigurationRequest = 121,
        VoiceAssistantConfigurationResponse = 122,
        VoiceAssistantSetConfiguration = 123,
        NoiseEncryptionSetKeyRequest = 124,
        NoiseEncryptionSetKeyResponse = 125,
        BluetoothScannerStateResponse = 126,
        BluetoothScannerSetModeRequest = 127,
        ZWaveProxyFrame = 128,
        ZWaveProxyRequest = 129,
        HomeassistantActionResponse = 130,
    }

    /// <summary>
    /// Minimal client stub for ESPHome Native API.
    /// </summary>
    public class SessionBase
    {
        protected NetworkStream networkStream;

        /// RPC hello(HelloRequest) returns (HelloResponse)
        public virtual async Task HelloAsync(HelloRequest request, CancellationToken ct = default)
        {
            await FrameHelper.WriteMessageAsync(networkStream, EspHomeApiMessageId.HelloResponse, request, ct).ConfigureAwait(false);
        }

        /// RPC authenticate(AuthenticationRequest) returns (AuthenticationResponse)
        public virtual async Task AuthenticateAsync(AuthenticationRequest request, CancellationToken ct = default)
        {
            await FrameHelper.WriteMessageAsync(networkStream, EspHomeApiMessageId.AuthenticationResponse, request, ct).ConfigureAwait(false);
        }

        /// RPC disconnect(DisconnectRequest) returns (DisconnectResponse)
        public virtual async Task DisconnectAsync(DisconnectRequest request, CancellationToken ct = default)
        {
            await FrameHelper.WriteMessageAsync(networkStream, EspHomeApiMessageId.DisconnectResponse, request, ct).ConfigureAwait(false);
        }

        /// RPC ping(PingRequest) returns (PingResponse)
        public virtual async Task PingAsync(PingRequest request, CancellationToken ct = default)
        {
            await FrameHelper.WriteMessageAsync(networkStream, EspHomeApiMessageId.PingResponse, request, ct).ConfigureAwait(false);
        }

        /// RPC device_info(DeviceInfoRequest) returns (DeviceInfoResponse)
        public virtual async Task Device_InfoAsync(DeviceInfoRequest request, CancellationToken ct = default)
        {
            await FrameHelper.WriteMessageAsync(networkStream, EspHomeApiMessageId.DeviceInfoResponse, request, ct).ConfigureAwait(false);
        }

        /// RPC list_entities(ListEntitiesRequest) returns (void)
        public virtual Task List_EntitiesAsync(ListEntitiesRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC subscribe_states(SubscribeStatesRequest) returns (void)
        public virtual Task Subscribe_StatesAsync(SubscribeStatesRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC subscribe_logs(SubscribeLogsRequest) returns (void)
        public virtual Task Subscribe_LogsAsync(SubscribeLogsRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC subscribe_homeassistant_services(SubscribeHomeassistantServicesRequest) returns (void)
        public virtual Task Subscribe_Homeassistant_ServicesAsync(SubscribeHomeassistantServicesRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC subscribe_home_assistant_states(SubscribeHomeAssistantStatesRequest) returns (void)
        public virtual Task Subscribe_Home_Assistant_StatesAsync(SubscribeHomeAssistantStatesRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC execute_service(ExecuteServiceRequest) returns (void)
        public virtual Task Execute_ServiceAsync(ExecuteServiceRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC noise_encryption_set_key(NoiseEncryptionSetKeyRequest) returns (NoiseEncryptionSetKeyResponse)
        public virtual async Task Noise_Encryption_Set_KeyAsync(NoiseEncryptionSetKeyRequest request, CancellationToken ct = default)
        {
            await FrameHelper.WriteMessageAsync(networkStream, EspHomeApiMessageId.NoiseEncryptionSetKeyResponse, request, ct).ConfigureAwait(false);
        }

        /// RPC button_command(ButtonCommandRequest) returns (void)
        public virtual Task Button_CommandAsync(ButtonCommandRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC camera_image(CameraImageRequest) returns (void)
        public virtual Task Camera_ImageAsync(CameraImageRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC climate_command(ClimateCommandRequest) returns (void)
        public virtual Task Climate_CommandAsync(ClimateCommandRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC cover_command(CoverCommandRequest) returns (void)
        public virtual Task Cover_CommandAsync(CoverCommandRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC date_command(DateCommandRequest) returns (void)
        public virtual Task Date_CommandAsync(DateCommandRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC datetime_command(DateTimeCommandRequest) returns (void)
        public virtual Task Datetime_CommandAsync(DateTimeCommandRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC fan_command(FanCommandRequest) returns (void)
        public virtual Task Fan_CommandAsync(FanCommandRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC light_command(LightCommandRequest) returns (void)
        public virtual Task Light_CommandAsync(LightCommandRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC lock_command(LockCommandRequest) returns (void)
        public virtual Task Lock_CommandAsync(LockCommandRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC media_player_command(MediaPlayerCommandRequest) returns (void)
        public virtual Task Media_Player_CommandAsync(MediaPlayerCommandRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC number_command(NumberCommandRequest) returns (void)
        public virtual Task Number_CommandAsync(NumberCommandRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC select_command(SelectCommandRequest) returns (void)
        public virtual Task Select_CommandAsync(SelectCommandRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC siren_command(SirenCommandRequest) returns (void)
        public virtual Task Siren_CommandAsync(SirenCommandRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC switch_command(SwitchCommandRequest) returns (void)
        public virtual Task Switch_CommandAsync(SwitchCommandRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC text_command(TextCommandRequest) returns (void)
        public virtual Task Text_CommandAsync(TextCommandRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC time_command(TimeCommandRequest) returns (void)
        public virtual Task Time_CommandAsync(TimeCommandRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC update_command(UpdateCommandRequest) returns (void)
        public virtual Task Update_CommandAsync(UpdateCommandRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC valve_command(ValveCommandRequest) returns (void)
        public virtual Task Valve_CommandAsync(ValveCommandRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC subscribe_bluetooth_le_advertisements(SubscribeBluetoothLEAdvertisementsRequest) returns (void)
        public virtual Task Subscribe_Bluetooth_Le_AdvertisementsAsync(SubscribeBluetoothLEAdvertisementsRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC bluetooth_device_request(BluetoothDeviceRequest) returns (void)
        public virtual Task Bluetooth_Device_RequestAsync(BluetoothDeviceRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC bluetooth_gatt_get_services(BluetoothGATTGetServicesRequest) returns (void)
        public virtual Task Bluetooth_Gatt_Get_ServicesAsync(BluetoothGATTGetServicesRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC bluetooth_gatt_read(BluetoothGATTReadRequest) returns (void)
        public virtual Task Bluetooth_Gatt_ReadAsync(BluetoothGATTReadRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC bluetooth_gatt_write(BluetoothGATTWriteRequest) returns (void)
        public virtual Task Bluetooth_Gatt_WriteAsync(BluetoothGATTWriteRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC bluetooth_gatt_read_descriptor(BluetoothGATTReadDescriptorRequest) returns (void)
        public virtual Task Bluetooth_Gatt_Read_DescriptorAsync(BluetoothGATTReadDescriptorRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC bluetooth_gatt_write_descriptor(BluetoothGATTWriteDescriptorRequest) returns (void)
        public virtual Task Bluetooth_Gatt_Write_DescriptorAsync(BluetoothGATTWriteDescriptorRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC bluetooth_gatt_notify(BluetoothGATTNotifyRequest) returns (void)
        public virtual Task Bluetooth_Gatt_NotifyAsync(BluetoothGATTNotifyRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC subscribe_bluetooth_connections_free(SubscribeBluetoothConnectionsFreeRequest) returns (BluetoothConnectionsFreeResponse)
        public virtual async Task Subscribe_Bluetooth_Connections_FreeAsync(SubscribeBluetoothConnectionsFreeRequest request, CancellationToken ct = default)
        {
            await FrameHelper.WriteMessageAsync(networkStream, EspHomeApiMessageId.BluetoothConnectionsFreeResponse, request, ct).ConfigureAwait(false);
        }

        /// RPC unsubscribe_bluetooth_le_advertisements(UnsubscribeBluetoothLEAdvertisementsRequest) returns (void)
        public virtual Task Unsubscribe_Bluetooth_Le_AdvertisementsAsync(UnsubscribeBluetoothLEAdvertisementsRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC bluetooth_scanner_set_mode(BluetoothScannerSetModeRequest) returns (void)
        public virtual Task Bluetooth_Scanner_Set_ModeAsync(BluetoothScannerSetModeRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC subscribe_voice_assistant(SubscribeVoiceAssistantRequest) returns (void)
        public virtual Task Subscribe_Voice_AssistantAsync(SubscribeVoiceAssistantRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC voice_assistant_get_configuration(VoiceAssistantConfigurationRequest) returns (VoiceAssistantConfigurationResponse)
        public virtual async Task Voice_Assistant_Get_ConfigurationAsync(VoiceAssistantConfigurationRequest request, CancellationToken ct = default)
        {
            await FrameHelper.WriteMessageAsync(networkStream, EspHomeApiMessageId.VoiceAssistantConfigurationResponse, request, ct).ConfigureAwait(false);
        }

        /// RPC voice_assistant_set_configuration(VoiceAssistantSetConfiguration) returns (void)
        public virtual Task Voice_Assistant_Set_ConfigurationAsync(VoiceAssistantSetConfiguration request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC alarm_control_panel_command(AlarmControlPanelCommandRequest) returns (void)
        public virtual Task Alarm_Control_Panel_CommandAsync(AlarmControlPanelCommandRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC zwave_proxy_frame(ZWaveProxyFrame) returns (void)
        public virtual Task Zwave_Proxy_FrameAsync(ZWaveProxyFrame request, CancellationToken ct = default) { return Task.CompletedTask; }

        /// RPC zwave_proxy_request(ZWaveProxyRequest) returns (void)
        public virtual Task Zwave_Proxy_RequestAsync(ZWaveProxyRequest request, CancellationToken ct = default) { return Task.CompletedTask; }

    } // class SessionBase

} // namespace IHC485.ESPHomeServerApi