name: Publish Selected Files to Public Repo

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Copy only the files/folders you want public
      - name: Prepare export folder
        run: |
          mkdir Projects
          cp IHC/IHC_Services -r Projects/

      # Push to public repo
      - name: Push to public repo
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.PUBLIC_REPO_DEPLOY_KEY }}
          external_repository: Soren-lofvall/public
          publish_branch: main
          publish_dir: Projects
